### ISSUE TITLE
关于sir论文section4节计算Cal-N指标的问题

### ISSUE THREAD

**Issue by HuXiLiFeng** [huangsg1/uncertainty-calibration#1]
你好，我在看SIR论文，文章思路很清晰，给我提供了不少思路。想请教个问题，在计算Cal-N指标的时候，我的理解是下面这样的，麻烦帮忙看看是不是我理解错了

在第四节计算值班表时，Consider Example 1 again, the Cal-N (N = 2) of the 20,000 samples is 2.4。那个例子里面，pcoc1=0.2/0.4=0.5；error1=1；pcoc2=0.8/0.6=4/3；error2=1/3。
那么算Cal-2=(1+1/9)/2再开根号，算出来也不是2.4

谢谢！

**Comment by huangsg1** [comment]
你好，感谢这么细致的读这篇文章。你算的是对的，文章给出的结果是错误的。
